### ISSUE TITLE
Change to isDirectoryWritable 

### ISSUE THREAD

**Issue by kdheepak** [PMeira/electricdss-src#3]
@PMeira I remember having to make a change to the [isDirectoryWritable function](https://github.com/PMeira/electricdss-src/blob/1528842ef9758ef8b334c2d66ca800c4c689007c/Source/Common/DSSGlobals.pas#L632-L640) to get it to work in order to fix of the issues I was having.

```pascal
function IsDirectoryWritable(const Dir: String): Boolean;
var
  TempFile: array[0..MAX_PATH] of Char;
begin
  if GetTempFileName(PChar(Dir), 'DA', 0, TempFile) <> 0 then
    {$IFDEF FPC}Result := DeleteFile(TempFile){$ELSE}Result := Windows.DeleteFile(TempFile){$ENDIF}
  else
    Result := False;
end;
```

This was a few months ago, and by the looks of it I had to do it only on Mac: see commit [here](https://github.com/NREL/OpenDSSDirect.py/commit/f7200b6c39d222c43ba4cd1a3a45afb17f76b6a5) for reference. If only I had been better about recording why I did that. I'll trace the exact change I made and share it here. I thought I'd post first to see if you find anything that is obvious just by looking at it.

**Comment by PMeira** [comment]
We can use [`FpAccess()`](https://www.freepascal.org/docs-html/rtl/baseunix/fpaccess.html) on MacOS and Linux. Do you remember if you used that?

**Comment by kdheepak** [comment]
I tried retracing the change. I think I know why I had to make the change but I don't know what change I made. It may not be directly related to the function linked to above. 

If you run the following, OpenDSS opens a text editor with the Y Matrix on a Mac. 

```
import opendssdirect as dss
dss.run_command("Redirect ./tests/data/13Bus/IEEE13Nodeckt.dss")
dss.run_command("Show Y")
```

But on Windows it opens a text editor with the Y Matrix AND also writes the Y Matrix to a file on disk in the current working directory I believe. I made a change that made the behavior similar for OpenDSS on Windows and on a Mac.

**Comment by PMeira** [comment]
@kdheepak OK, I'll check that. I switched to `FpAccess` after testing it.

**Comment by PMeira** [comment]
@kdheepak It writes the output file in the current OutputDirectory, which defaults to value of DataPath. But without the `FpAccess` change in `IsDirectoryWritable`, it mishandled the DataPath and the OutputDirectory (this one needs to be writeable). The file ended up in `/tmp/OpenDSSCmd`, which is the default temporary dir.

So, after the patch in 7d69e5a, since I previously disabled the .ini handling completely in https://github.com/PMeira/electricdss-src/commit/1528842ef9758ef8b334c2d66ca800c4c689007c:
- The default DataPath is set to the current working directory -- it doesn't go to whatever was the last folder since, at least nowadays, it doesn't make much sense for a library to do that on start-up, especially if the user is running multiple instances.
- If you "compile" a DSS script, it should by default create the output in the same folder as the script if that is writeable, otherwise it will end up in `/tmp/OpenDSSCmd` still.
- If you don't change the initial datapath at any point, it will end up in the initial working directory when dss_capi is loaded (again if it is writable). 

Ideally the current working dir should never be touched but that would need more intrusive changes. Maybe someday...

**Comment by kdheepak** [comment]
Great! I think this is perfect for now! I now remember the temporary directory thing happening. Thanks for the quick response as always!
